return {
  server_error = 'serverError',
  invalid_expire = 'invalidExpire',
  invalid_encrypted = 'invalidEncrypted',
  invalid_thumb = 'invalidThumb',
  db_error = 'dbError',
  failed_to_write = 'failedToWrite',
  invalid_request_id = 'invalidRequestId',
  invalid_request_pass = 'invalidRequestPass',
  no_file = 'noFile',
  invalid_password = 'invalidPassword',
  failed_to_remove = 'failedToRemove',
  ip_limit = 'ipLimit',
  hidden_limit = 'hiddenLimit',
}
